### ISSUE TITLE
Duplicate Purchase event issue

### ISSUE THREAD

**Issue by rihale** [gtm-server/facebook-tag#1]
I am sending through GTM a purchase event using the GA4 client, the event is being received as a single purchase event, but is generating 2 events in Facebook, I have 2 ad accounts but can see the separate requests, but I also see on the console the raw and mapped data, not sure what to do there is only one event on the client, and one event coming into the GTM server but 2 pixel events in Facebook. There is no other code generating a pixel purchase event

**Comment by Bukashk0zzz** [comment]
Do you send this event on Web container also or only thru server side? (If you have web pixel events might be duplicated) Other users don't have duplication issue. Look like problem with your setup.

**Comment by Bukashk0zzz** [comment]
In any way we have now deduplication solution for Facebook tag and that's why I close this issue. https://gtm-server.com/how-to-set-up-facebook-event-deduplication-in-google-tag-manager/
