### ISSUE TITLE
fbp&fbc should be set by us?

### ISSUE THREAD

**Issue by ghostiq** [gtm-server/facebook-tag#2]
Hi there,

What do we need to change/configure in order to use remarketing? Do we need at least to autogenerate fbp (or get from cookie if exists), the same linke fbc? Should we modify tag code?

**Comment by Bukashk0zzz** [comment]
Hi,

You can use this tag for remarking. This tag already handle fbc and fbp cookies. 
Check code https://github.com/gtm-server/facebook-tag/blob/main/template.tpl#L415

Also fbc, fbp can't be generated. If you want to achieve better "Event Matching" score you need to send as much as possible user data parameters documentation for this https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/customer-information-parameters/

**Comment by ghostiq** [comment]
I believe setting fbp cookie is missing. If I have pixel installed fbp is set. If I use a client fbp is missing.

fbp
When the Facebook pixel is installed on a website, and the pixel uses first-party cookies, the pixel automatically saves a unique identifier to an _fbp cookie for the website domain if one does not already exist.

I believe I can generate it in a similar way to fbc:
if (!fbp) {
        fbp = 'fb.1.' + getTimestampMillis() + '.' + generateRandom(100000000, 2147483647);
}

**Comment by Bukashk0zzz** [comment]
As I write in the previous message you can't generate fbp parameter by yourself. If you want to generate a unique identifier of the user you can use External ID more info here https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/external-id and also compression of external id and fbp parameters https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/external-id#fbp-parameter

This tag for sure works with fbp and fbc cookies. I think the main problem that you try to set them on the browser and then us on server. You need to set them from server. Basically, fbc already generated autometicali from the fbclick parameter on the server, and fbp can be generated by other server tag/client.

**Comment by ghostiq** [comment]
Okay, so just to confirm I can use facebook remarketing for someone who visit my site (came from different source like google organic / no interact with facebook)? I need to set a fb remarketing campaign for people who visited my website already (not through facebook)?

**Comment by Bukashk0zzz** [comment]
If a user comes to the site without fbclick parameter. For example Google, in this case, there will be not set any additional cookie to this user. Basically, you can use google fpid cookie like external ID parameter for Facebook if you want (but I don't recommend it). There is no reason to set any additional cookies for the user because this not help Facebook to match the user.

**Comment by Bukashk0zzz** [comment]
Closed due to inactivity.

**Comment by ajtatum** [comment]
I'd like to reopen this issue as I think it's important that a fbp and fbc cookie is generated appropriately. When making a request to Facebook, it has the "very_important_cookies" and checks for these cookie values, but they don't exist. I'm not sure if I should send FPID, FPID2 in place of fbp and FPCL in place of fbc.
