### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [gtm-server/facebook-tag#4]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) We see console errors while doing "run code". Can you please resolve the issue.
![Screenshot 2021-03-31 11 56 29 AM](https://user-images.githubusercontent.com/53495700/113196360-45a14780-9218-11eb-86b9-848fd7d7df50.png)

**Comment by Bukashk0zzz** [comment]
Thanks for review. This bug is fixed.
