### ISSUE TITLE
Invalid Input in Template Preview Error

### ISSUE THREAD

**Issue by gentlee66** [gtm-server/facebook-tag#5]
When importing the template.tpl file into Tag Templates, I'm getting an "Invalid input in Template Preview" error and then I can't use the template when creating a tag. Was trying to debug but the error isn't very helpful. Please see the screenshot:
![Screen Shot 2021-04-23 at 9 19 46 PM](https://user-images.githubusercontent.com/26042660/115942853-38bfee80-a47a-11eb-88d7-9c03783de5e0.png)

**Comment by Bukashk0zzz** [comment]
That's because you tried to import template into GTM Web container. This template for GTM Server container. 

You can follow this guide on how to setup it https://gtm-server.com/how-to-set-up-facebook-conversion-api/
