### ISSUE TITLE
Server Side - Facebook Parameters Invalid

### ISSUE THREAD

**Issue by MYTurk** [gtm-server/facebook-tag#6]
Hi,
Thanks for your valuable input on Facebook Conversion API. In the course of our implementation we have faced some issues. We haved used inherit method to send events to server containers facebook tag.
First of all the pageview and impression tags we have on the web container for view item, add to cart, checkout and purchase are not working as server side tags. Some parameters have errors.  Could you help us with this? Is there something we are doing wrong?
Secondly although we have currency and value sent as facebook parameters, we are getting errors? Could you explain us, which steps we need to follow here?
Thank you for your support.
Best regards,
You can find the errors we are reciveing in the screenshots attached.

![serverside-console](https://user-images.githubusercontent.com/85285516/120631622-c0811b80-c470-11eb-9400-03bbc9d1374c.png)
![view_item-400](https://user-images.githubusercontent.com/85285516/120631626-c2e37580-c470-11eb-96f6-8180751d8ad2.png)
![gtmserverside](https://user-images.githubusercontent.com/85285516/120631630-c37c0c00-c470-11eb-9f3c-60d149630e34.png)

**Comment by Bukashk0zzz** [comment]
Please check our tutorial on [how to debug FB CAPI](https://gtm-server.com/how-to-check-if-universal-analytics-ga4-server-side-tracking-and-facebook-conversion-api-work-correctly/)

I see errors on your screenshot but I don't understand what exactly written there.
Request tab -> under Outgoing HTTP Requests click on Facebook request -> Scroll down and check Response Body -> use one of the decoders to understand the error message. 


We provide paid consultation and help with CAPI setup. If you interested please leave a request here https://gtm-server.com/agency/ or write an email to support@gtm-server.com
