### ISSUE TITLE
This template is not compatible with Web Containers Error

### ISSUE THREAD

**Issue by kkbharankar** [gtm-server/facebook-tag#7]
We are facing this template is not compatible with Web Containers after importing this template.

Check below image
https://lh3.googleusercontent.com/-srDhdmC4RbQ/YNntQwGNmqI/AAAAAAAAB5Y/vtSYRjT3PsUzlqo75TywbAYuEjPT3cKxACJEEGAsYHg/s0/2021-06-28.png?authuser=0

**Comment by Bukashk0zzz** [comment]
That's correct. This template for the GTM Server Side container. 
You can find more info on how to use it by the link: https://stape.io/how-to-set-up-facebook-conversion-api/
